---
title: "normalise_fams"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. read in file and normalise to avergae of two read no.s
library(readr)
X8mega_readygraph <- read_csv("~/thesis/python_r/1final_data/8mega_work_files/graphing_stage_normafams1.5/8mega_readygraph.csv")
X8mega_readygraph
attach(X8mega_readygraph)

x <- Cluster_count[1:22]/122750
y <- Cluster_count[23:38]/192020

xby100k <- x*157385
yby100k <- y*157385

X8mega_readygraph$Cluster_count <- c(xby100k,yby100k)
X8mega_readygraph

final <- X8mega_readygraph[2:4]
final

#2. #load libares to graph
library(dplyr)
library(ggplot2)

#direct input from above
g <- final
g

rb <- ggplot(g, aes(x = Cluster_type, y=Cluster_count, fill=CRC_or_Normal)) +
  geom_col(data = g, aes(y = Cluster_count, fill = CRC_or_Normal), 
              position = position_dodge(preserve = "single"), width =0.8) +
  scale_y_continuous(breaks = seq(0,800, by = 10), expand=c(0,0)) +
  scale_fill_manual(values = c("#eb3f36", "#3062e3"), name = "Patient Status") +
  scale_x_discrete(expand=c(0,0)) +
   ggtitle("Megahit Contigs BGCs") +
  xlab("BGC Type") +
  ylab("Number of BGCs") +
  
theme(
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.x = element_text(size=10, margin = margin(t = -15, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle=45, vjust = 1.05, hjust = 1, size = 5),
        axis.text.y = element_text(size=7),
        axis.title.y = element_text(size=10),
        legend.text = element_text(size=10),
        legend.key.size = unit(0.8,"line"),
        legend.title = element_text(size = 12),
        legend.position = c(0.9,0.9),
        panel.background = element_blank(),
        #panel.grid.major.y = element_line(size = 0.3, linetype = 'solid', colour = "white"),
        panel.ontop = TRUE,
       ) +

theme(axis.line.x = element_line(color="black", size = 0.25),
        axis.line.y = element_line(color="black", size = 0.25))

rb

ggsave("rb.png", device = "png")


```
```

